version: "3.8"
services:
  app:
    build: ./infra/app
    volumes:
      - ./laravel:/work
    ports:
      - 9001:9001
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-welcome}
      - DB_USERNAME=${DB_USER:-welcomeuser}
      - DB_PASSWORD=${DB_PASS:-adminpassword}

  nginx:
    # nginxの公式イメージ（偶数が安定バージョンらしい）
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./laravel:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  # 公式イメージをそのまま利用
  mysql:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME:-welcome}
      - MYSQL_USER=${DB_USER:-welcomeuser}
      - MYSQL_PASSWORD=${DB_PASS:-adminpassword}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-adminpassword}

volumes:
  db-store:
